#!/bin/bash
echo ""[DBest School[" > '\*\\'"Best School"\'\\*$\?\*\*\*\*\*:)'[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[D[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C\"[D[C[[3~[3~[3~[3~[3~[3~[3~[3~[3~[3~[3~[3~[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C\'\""Best School"\'\"\\*$\?\*\*\*\*\*:)"
